### ISSUE TITLE
Move clock

### ISSUE THREAD

**Issue by jrappen** [deathaxe/sublime-clock#2]
I suggest moving the clock to where sidebar and tabbar intersect.

Compare screenshots from: <https://github.com/poucotm/Guna>

---

Not sure how to add to the current theme of the active window...live, though.

**Comment by deathaxe** [comment]
1. Guna changes the theme and updates it after each minute.
2. This way of printing the time is too obtrusive

Both are not the intention of this plugin.

Wontfix.
